# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MGB_InputTool
                                 A QGIS plugin
 This plugin prepares the data for the MGB-IPH model.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-24
        copyright            : (C) 2024 by André Rodrigues da Silva
        email                : andrerodriguessilva99@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MGB_InputTool class from file MGB_InputTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MGBInputTool import MGB_InputTool
    return MGB_InputTool(iface)
